dialects_dict = {
    3: "EG",
    11: "PL",
    6: "KW", 
    8: "LY",
    12: "QA",
    5: "JO",
    7: "LB",
    13: "SA",
    0: "AE",
    1: "BH",
    10: "OM",
    15: "SY",
    2: "DZ",
    4: "IQ",
    9: "MA",
    17: "YE",
    16: "TN",
    14: "SD"
}